### ISSUE TITLE
Implement try count and try interval for schedules

### ISSUE THREAD

**Issue by insolite** [insolite/alarme#1]
`try_count` - Default `null` - infinite
`try_interval` - Default 1 (in seconds)

```yaml
schedules:
  try_count: 6
  try_interval: 10
  start:
    actions:
      - email_start
      - set_state_pass
    run_count: 1
```
